"""empty message

Revision ID: f911ca702028
Revises: 
Create Date: 2021-11-08 11:49:34.850620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f911ca702028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('userType', sa.Enum('Student', 'Lector'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseName', sa.String(length=150), nullable=False),
    sa.Column('courseDescription', sa.String(length=500), nullable=False),
    sa.Column('courseLector', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseLector'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['course.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('requestToCourse', sa.Integer(), nullable=False),
    sa.Column('requestToLector', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OnHold', 'Accepted', 'Declined'), nullable=False),
    sa.ForeignKeyConstraint(['requestToCourse'], ['course.id'], ),
    sa.ForeignKeyConstraint(['requestToLector'], ['user.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('courseMember')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
